---
apiVersion: v1
kind: Service
metadata:
  name: logstash-service
  labels:
    app: logstash
spec:
  selector:
    app: logstash
  type: NodePort
  ports:
  - name: logstash-beats
    port: 5044
    targetPort: 5044
    nodePort: 30004
  - name: logstash-monitor
    port: 9600
    targetPort: 9600
    nodePort: 30003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-deploy
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      name: logstash-pod
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash-con
        image: logstash:7.7.1
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/logstash/pipeline
        ports:
            - name: beats
              containerPort: 5044
            - name: logstash
              containerPort: 9600
      volumes:
      - name: config-volume
        configMap:
          name: logstash-conf


         