apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-conf
  labels:
    app: logstash
data:
  logstash.conf: |-
    input {
      beats {
        port => 5044
      }
    }
    filter {
      grok {
        match => [ "message" , "%{COMBINEDAPACHELOG}"]
      }
      mutate {
        convert => ["bytes", "integer"]
      }
      geoip {
        source => "clientip"
      }
      date {
        match => [ "timestamp" , "dd/MMM/YYYY:HH:mm:ss Z" ]
        locale => en
        remove_field => [ "timestamp" ]
      }
      useragent {
        source => "agent"
        target => "useragent"
      }
    }
    output {
      elasticsearch {
        hosts => ["elasticsearch"]
        index => "webdb"
        document_type=> "weblog" 
      }
      stdout {
         codec => "rubydebug"
      }
    }
