apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-conf
  labels:
    app: logstash
data:
  logstash.conf: |-
    input{
      beats {
        port => 5044
        id => "my_plugin_id"
      }
    }
    filter {
      grok {
        match => [ "message" , "%{COMBINEDAPACHELOG}+%{GREEDYDATA:extra_fields}"]
        overwrite => [ "message" ]
      }
      mutate {
        convert => ["response", "integer"]
        convert => ["bytes", "integer"]
        convert => ["responsetime", "float"]
      }
      geoip {
        source => "clientip"
        target => "geoip"
        add_tag => [ "geoip" ]
      }
      date {
        match => [ "timestamp" , "dd/MMM/YYYY:HH:mm:ss Z" ]
        remove_field => [ "timestamp" ]
      }
      useragent {
        source => "agent"
      }
    }
    output {
      elasticsearch {
        hosts => ["elasticsearch"]
        index => "%{[@metadata][beat]}-%{[@metadata][version]}" 
      }
      stout {
         codec => "rubydebug"
      }
    }
